FROM perl

COPY . /code
WORKDIR /code

RUN cpanm App::cpm && cpm install -g Carton && cpm install

EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/carton", "exec", "perl", "local/bin/morbo", "script/cheese_cake"]
